using PIKA.Infraestructura.Comun;
using PIKA.Modelo.Metadatos;
using RepositorioEntidades;
using System;
using System.Collections.Generic;
using System.Text;
using System.Text.Json.Serialization;
using System.Xml.Serialization;

namespace PIKA.Modelo.Organizacion
{

    /// <summary>
    /// Rol laboral en la organización
    /// </summary>
    public class Rol : Entidad<string>, IEntidadNombrada, IEntidadRelacionada
    {

       [XmlIgnore]
       [JsonIgnore]
        public string TipoOrigenDefault => ConstantesModelo.IDORIGEN_DOMINIO;


        public Rol() {
            this.UsuariosRol = new HashSet<UsuariosRol>();
        }

        [Prop(OrderIndex: 0, IsId: true, Required: true, Autogenerated: false,
        HTMLControl: PropAttribute.HTML_HIDDEN)]
        [Tbl(OrderIndex: 0, Visible: false)]
        public override string Id { get => base.Id; set => base.Id = value; }

        /// <summary>
        /// Nombre del rol
        /// </summary>
        [Prop(OrderIndex: 1, Required: true, HTMLControl: PropAttribute.HTML_TEXT)]
        [Tbl(OrderIndex: 1)]
        [ValidString(minlen: 1, maxlen: 200)]
        public string Nombre {get; set;}

        /// <summary>
        /// Descripción del rol
        /// </summary>
        [Prop(OrderIndex: 2, Required: true, HTMLControl: PropAttribute.HTML_TEXT)]
        [Tbl(OrderIndex: 2)]
        [ValidString(minlen: 1, maxlen: 500)]
        public string Descripcion { get; set; }

        /// <summary>
        /// Los roles se relacionan con un dominio o una unidad organizacional
        /// que representa el contexto de uso para el rol
        /// Los roles de de dominios son globales a la organización
        /// Los roles de unidad oerganizacional sólo son aplicables a la OU
        /// </summary>
        [Prop(OrderIndex: 3, Required: true, HTMLControl: PropAttribute.HTML_HIDDEN)]
        public string TipoOrigenId {get; set;}

        /// <summary>
        /// Identificador único del dominio que contiene los roles
        /// </summary>
        [Prop(OrderIndex: 4, Required: true, HTMLControl: PropAttribute.HTML_HIDDEN)]
        public string OrigenId {get; set;}

        
        /// <summary>
        /// USuarios participantes en el rol
        /// </summary>
        [XmlIgnore]
        [JsonIgnore]
        public ICollection<UsuariosRol> UsuariosRol { get; set; }
    }
}
