using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;

namespace PIKA.Modelo.Metadatos
{
    [AttributeUsage(AttributeTargets.All, AllowMultiple = false, Inherited = false)]
    public class PropAttribute : Attribute
    {

        public const string HTML_CHECKBOX = "checkbox";
        public const string HTML_DATE = "date";
        public const string HTML_TIME = "time";
        public const string HTML_DATETIME = "datetime-local";
        public const string HTML_FILE = "file";
        public const string HTML_HIDDEN = "hidden";
        public const string HTML_NUMBER = "number";
        public const string HTML_RADIO = "radio";
        public const string HTML_TEXT = "text";
        public const string HTML_TEXTAREA = "textarea";
        public const string HTML_SELECT = "select";



        [Flags]
        public enum CRUDActions
        {
            none = 0, read = 1, write = 2, delete = 4
        }

        private string _Id;
        private string _I18nNameId;
        private string _Type;
        private string _HTMLControl;
        private int _OrderIndex;
        private CRUDActions _actions;
        private bool _Searchable;
        private bool _Orderable;
        private bool _Visible;
        private bool _IsId;
        private bool _IsFKId;
        private bool _Required;
        private bool _Autogenerated;
        private bool _IskeyValue;
        private string _DefaultValue;
        private bool _IsHieId;
        private bool _IsHieText;
        private bool _IsHieParentId;
        private bool _IsHieFilter;

        public virtual bool Required
        {
            get { return _Required; }
        }
        public virtual bool Autogenerated
        {
            get { return _Autogenerated; }
        }

        public virtual bool IsId
        {
            get { return _IsId; }
        }

        public virtual bool IsFKId
        {
            get { return _IsFKId; }
        }

        public virtual bool IskeyValue
        {
            get { return _IskeyValue; }
        }

        public virtual bool IsHieId
        {
            get { return _IsHieId; }
        }


        public virtual bool IsHieText
        {
            get { return _IsHieText; }
        }

        public virtual bool IsHieParentId
        {
            get { return _IsHieParentId; }
        }

       public virtual bool IsHieFilter
        {
            get { return _IsHieFilter; }
        }

        public PropAttribute(string HTMLControl = HTML_TEXT, string Type = "",
            [CallerMemberName] string I18nNameId = null, object DefaultValue = null,
            int OrderIndex = 0, bool Searchable = true, bool Orderable = true, bool Visible = true,
            bool IsId = false, bool IsFKId = false, bool Required = false, bool Autogenerated = false,
            bool isHieId=false, bool isHieText = false, bool isHieParentId = false, bool isHieFilter = false,
            CRUDActions actions = CRUDActions.read | CRUDActions.write | CRUDActions.delete)
        {

            this._HTMLControl = HTMLControl;
            this._IskeyValue = IskeyValue;
            this._IsId = IsId;
            this._IsFKId = IsFKId;
            this._Required = Required;
            this._Autogenerated = Autogenerated;
            this._Visible = Visible;
            this._Orderable = Orderable;
            this._Searchable = Searchable;
            this._Type = Type;
            this._I18nNameId = I18nNameId;
            this._OrderIndex = OrderIndex;
            this._actions = actions;
            this._IsHieFilter = isHieFilter;
            this._IsHieId = isHieId;
            this._IsHieParentId = isHieParentId;
            this._IsHieText = IsHieText;

        }

        public virtual int CrudActions
        {
            get { return _actions.GetHashCode(); }
        }

        public virtual string HTMLControl
        {
            get { return _HTMLControl; }
        }

        public virtual int OrderIndex
        {
            get { return _OrderIndex; }
        }

        public virtual string Id
        {
            get { return _Id; }
        }

        public virtual string Type
        {
            get { return _Type; }
        }

        public virtual bool Orderable
        {
            get { return _Orderable; }
        }

        public virtual bool Searchable
        {
            get { return _Searchable; }
        }



        public virtual bool Visible
        {
            get { return _Visible; }
        }

        public virtual string I18nNameId
        {
            get { return _I18nNameId; }
        }

        public virtual string DefaultValue
        {
            get { return _DefaultValue; }
        }

    }
}
