using PIKA.Infraestructura.Comun;
using PIKA.Modelo.Metadatos;
using RepositorioEntidades;
using System;
using System.Collections.Generic;
using System.Text;
using System.Text.Json.Serialization;
using System.Xml.Serialization;

namespace PIKA.Modelo.Organizacion
{

    /// <summary>
    /// Detalla la ubicació espacial de un elemento en forma de una dirección postal
    /// Las direcciones postales se  enlazan a los objeto a através de una entidad de relación
    /// con la finalidad de establecer relaciones varios a varios
    /// </summary>
    public class DireccionPostal : Entidad<string>, IEntidadNombrada, IEntidadRelacionada
    {
     
        [XmlIgnore]
        [JsonIgnore]
        public string TipoOrigenDefault => ConstantesModelo.IDORIGEN_NULO;


        public DireccionPostal()
        {
            this.TipoOrigenId = this.TipoOrigenDefault;
        }


        /// <summary>
        /// Identificador únioc de la dirección postal
        /// </summary>
        [Prop(OrderIndex: 0, IsId: true, Required: true, Autogenerated: false,
        HTMLControl: PropAttribute.HTML_HIDDEN)]
        [Tbl(OrderIndex: 0, Visible: false)]
        public override string Id { get => base.Id; set => base.Id = value; }


        /// <summary>
        /// NOmbre corto para reconocer la dirección por ejemplo: Casa, Oficina, etc
        /// </summary>
        [Prop(OrderIndex: 1, Required: true, HTMLControl: PropAttribute.HTML_TEXT)]
        [Tbl(OrderIndex: 1)]
        [ValidString(minlen: 1, maxlen: 200)]
        public string Nombre { get; set; }


        /// <summary>
        /// Calle de la dirección
        /// </summary>
        [Prop(OrderIndex: 2, Required: true, HTMLControl: PropAttribute.HTML_TEXT)]
        [Tbl(OrderIndex: 2)]
        [ValidString(minlen: 1, maxlen: 200)]
        public string Calle { get; set; }

        /// <summary>
        /// No. interior de la dirección
        /// </summary>
        [Prop(OrderIndex: 3, Required: true, HTMLControl: PropAttribute.HTML_TEXT)]
        [Tbl(OrderIndex: 3)]
        public string NoInterno { get; set; }


        /// <summary>
        /// No. exterior de la dirección
        /// </summary>
        [Prop(OrderIndex: 4, Required: true, HTMLControl: PropAttribute.HTML_TEXT)]
        [Tbl(OrderIndex: 4)]
        public string NoExterno { get; set; }


        /// <summary>
        /// Colonia o barrio de la dirección
        /// </summary>
        [Prop(OrderIndex: 5, Required: true, HTMLControl: PropAttribute.HTML_TEXT)]
        [Tbl(OrderIndex: 5)]
        public string Colonia { get; set; }


        /// <summary>
        /// Código postal de la dirección
        /// </summary>
        [Prop(OrderIndex: 6, Required: true, HTMLControl: PropAttribute.HTML_TEXT)]
        [Tbl(OrderIndex: 6)]
        public string CP { get; set; }


        /// <summary>
        /// Municipio o alcaldía de la dirección
        /// </summary>
        [Prop(OrderIndex: 7, Required: true, HTMLControl: PropAttribute.HTML_TEXT)]
        [Tbl(OrderIndex: 7)]
        public string Municipio { get; set; }


        /// <summary>
        /// Estado del país de la dirección
        /// </summary>
        [Prop(OrderIndex: 8, Required: true, HTMLControl: PropAttribute.HTML_SELECT)]
        [Tbl(OrderIndex: 8)]
        public string EstadoId { get; set; }


        /// <summary>
        /// País de la dirección
        /// </summary>
        [Prop(OrderIndex: 9, Required: true, HTMLControl: PropAttribute.HTML_SELECT)]
        [Tbl(OrderIndex: 9)]
        public string PaisId { get; set; }



        /// <summary>
        /// Tipo de ojeto origen asociado a la dirección, pr ejemplo UO
        /// </summary>
        [Prop(OrderIndex: 10, Required: true, HTMLControl: PropAttribute.HTML_HIDDEN)]
        public string TipoOrigenId { get; set; }


        /// <summary>
        /// Identificador único del objeto origen, por ejemplo el id de una UO
        /// </summary>
        [Prop(OrderIndex: 11, Required: true, HTMLControl: PropAttribute.HTML_HIDDEN)]
        public string OrigenId { get; set; }

        /// <summary>
        /// Identifica si la dirección postal es la dirección por defecto para el origen
        /// </summary>
        public bool EsDefault { get; set; }

        public virtual Pais Pais { get; set; }

        public virtual Estado Estado { get; set; }
    }
}
