using PIKA.Infraestructura.Comun;
using PIKA.Modelo.Metadatos;
using RepositorioEntidades;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using static PIKA.Modelo.Metadatos.PropAttribute;

namespace PIKA.Modelo.Organizacion
{

    /// <summary>
    /// El dominio es el contenedor todos los recursos asociados a una organización
    /// </summary>
    [Entidad(EliminarLogico: true)]
    [EntidadVinculada(Entidad: "UnidadOrganizacional", Cardinalidad: TipoCardinalidad.UnoVarios, Padre: "Id", Hijo: "DominioId")]
    public class Dominio : Entidad<string>, IEntidadNombrada, IEntidadRelacionada, IEntidadEliminada
    {
        
        public string TipoOrigenDefault => ConstantesModelo.IDORIGEN_GLOBAL;

        public Dominio() {
            UnidadesOrganizacionales = new HashSet<UnidadOrganizacional>();
            this.TipoOrigenId = this.TipoOrigenDefault;
        }

        [Prop(OrderIndex: 0, IsId: true, Required: true, Autogenerated: false, 
            HTMLControl: PropAttribute.HTML_HIDDEN,  actions: CRUDActions.rwd)  ]
        [Tbl(OrderIndex: 0, Visible: false)]
        public override string Id { get => base.Id; set => base.Id = value; }


        [Prop(OrderIndex: 1, Required: true, HTMLControl: PropAttribute.HTML_TEXT,
            actions: CRUDActions.arwd)]
        [Tbl(OrderIndex: 1)]
        [ValidString(minlen: 1, maxlen: 200)]
        /// <summary>
        /// NOmbre de la unodad organizacional
        /// </summary>
        public string Nombre { get; set; }


        [Prop(OrderIndex: 2, Required: true, DefaultValue: "false", 
            HTMLControl: PropAttribute.HTML_TOGGLE, actions: CRUDActions.arwd)]
        [Tbl(OrderIndex: 2, Visible: true)]
        /// <summary>
        /// Especifica si el dominio ha sido eliminado de manera lógica
        /// </summary>
        public bool Eliminada { get; set; }

        /// <summary>
        /// Identificador de relación de origem, en este caso se utiliza
        /// para vincular la unidad con su dueño en el modo MultiTenant 
        /// </summary>
        [Prop(OrderIndex: 3, Required: true, HTMLControl: PropAttribute.HTML_HIDDEN, 
            DefaultValue: ConstantesModelo.IDORIGEN_GLOBAL, actions: CRUDActions.arwd)]
        public string TipoOrigenId { get; set; }

        /// <summary>
        /// Identficador único del dueño, TENANT
        /// El Id de ralción es el identificador de un dominio
        /// </summary>
        [Prop(OrderIndex: 4, Required: true, HTMLControl: PropAttribute.HTML_HIDDEN, 
            DefaultValue: ConstantesModelo.IDORIGEN_GLOBAL, actions: CRUDActions.arwd)]
        public string OrigenId { get; set; }

               
        /// <summary>
        /// Propiedad de navegación para unidades organizacionales
        /// </summary>
        public ICollection<UnidadOrganizacional> UnidadesOrganizacionales { get; set; }
        
    }
}
