using Microsoft.CodeAnalysis.CSharp.Syntax;
using PIKA.Modelo.Metadatos;
using RepositorioEntidades;
using System;
using System.Collections.Generic;
using System.Text;
using System.Text.Json.Serialization;
using System.Xml.Serialization;

namespace PIKA.Modelo.Organizacion
{

    /// <summary>
    /// Las unidades organizacionales agrupan recursos para la organización del trabajo
    /// </summary>
    public class UnidadOrganizacional : Entidad<string>, IEntidadNombrada, IEntidadEliminada
    {
        public const string CampoDominioId = "DominioId";
        

        [Prop(OrderIndex: 0, IsId: true, Required: true, Autogenerated: false,  HTMLControl: PropAttribute.HTML_HIDDEN)]
        [Tbl(OrderIndex: 0, Visible: false)]
        public override string Id { get => base.Id; set => base.Id = value; }


        [Prop(OrderIndex: 1, Required: true, HTMLControl: PropAttribute.HTML_TEXT)]
        [Tbl(OrderIndex: 1, Visible: true)]
        [ValidString(minlen: 1, maxlen: 100)]
        /// <summary>
        /// NOmbre de la unodad organizacional
        /// </summary>
        public string Nombre {get; set;}


        /// <summary>
        /// Destermina si la unidad ha sido eliminada
        /// </summary>
        [Prop(OrderIndex: 2, Required: true, DefaultValue: "false", HTMLControl: PropAttribute.HTML_CHECKBOX)]
        [Tbl(OrderIndex: 2, Visible: true)]
        public bool Eliminada {get; set;}

        /// <summary>
        /// Identiicador único del cominio al que se asocia la UO
        /// </summary>
        [Prop(OrderIndex: 3, Visible: false, HTMLControl: PropAttribute.HTML_HIDDEN)]
        public string DominioId { get; set; }

        [JsonIgnore]
        [XmlIgnore]
        public Dominio Dominio { get; set; }

    }
}
