using PIKA.Infraestructura.Comun;
using PIKA.Modelo.Metadatos;
using RepositorioEntidades;
using System;
using System.Collections.Generic;
using System.Text;

namespace PIKA.Modelo.Contenido
{
    public class Elemento : Entidad<string>, IEntidadRegistroCreacion, IEntidadEliminada, IEntidadRelacionada, IEntidadNombrada
    {
        public string TipoOrigenDefault => ConstantesModelo.IDORIGEN_UNIDAD_ORGANIZACIONAL;
        public Elemento() {
            this.TipoOrigenId = TipoOrigenDefault;
            this.Versiones = new HashSet<Version>();
            this.Vinculos = new HashSet<VinculoElemento>();
        }
        [Prop(OrderIndex: 0, IsId: true, Required: true, Autogenerated: false, HTMLControl: PropAttribute.HTML_HIDDEN)]
        [Tbl(OrderIndex: 0, Visible: false)]
        public override string Id { get => base.Id; set => base.Id = value; }


        [Prop(OrderIndex: 1, Required: true)]
        [Tbl(OrderIndex: 1)]
        [ValidString(minlen: 1, maxlen: 100)]
      
        /// <summary>
        /// Sombre común dado al elemento de contenido
        /// </summary>
        public string Nombre { get; set; }
        //#Requerido, longitud nombre

        /// <summary>
        /// Indica si el elemento ha sido eliminado de manera lógica
        /// </summary>
        public bool Eliminada { get; set; }
        //#Requerido default=false

        /// <summary>
        /// Tipo de origen del contenido, por defecto el contenido será propiedad de la Unidad Organizacional que gestiona 
        /// el reposotorio. El orign tambi´´ien puede ser ConstantesModelo.IDORIGEN_DOMINIO 
        /// </summary>
        public string TipoOrigenId { get; set; }
        //#Requerido, GUID

        /// <summary>
        /// Identificador único del origen por ejemplo el ID de la unidad organizaciónal
        /// </summary>
        public string OrigenId { get; set; }
        //#Requerido, GUID

        /// <summary>
        /// Identificador único del usuario que creó la entidad
        /// </summary>
        public string CreadorId { get; set; }
        //#Requerido, GUID


        /// <summary>
        /// Fecah de creación de la entidad en formato UTC
        /// </summary>
        public DateTime FechaCreacion { get; set; }
        //#Requerido

        ///// <summary>
        ///// Identificador único del volúmen para el contenido
        ///// </summary>
        //public string VolumenId { get; set; }

        /// <summary>
        /// Identificador único de la carpeta donde se creó el contenido
        /// </summary>
        public string CarpetaId { get; set; }
        // Es opcional

        /// <summary>
        /// Identificador únido del permiso asociado al elemeento
        /// </summary>
        public string PermisoId { get; set; }
        // Es opcional


        public ICollection<VinculoElemento> Vinculos { get; set; }
        public Permiso Permiso { get; set; }
        public virtual Volumen Volumen { get; set; }
        public virtual ICollection<Version> Versiones { get; set; }

        public virtual Parte Parte { get; set; }
    }
}
