using PIKA.Infraestructura.Comun;
using PIKA.Modelo.Metadatos;
using RepositorioEntidades;
using System;
using System.Collections.Generic;
using System.Text;

namespace PIKA.Modelo.Organizacion
{

    /// <summary>
    /// El dominio es el contenedor todos los recursos asociados a una organización
    /// </summary>
    public class Dominio : Entidad<string>, IEntidadNombrada, IEntidadRelacionada
    {
        
        public string TipoOrigenDefault => ConstantesModelo.IDORIGEN_GLOBAL;

        public Dominio() {
            UnidadesOrganizacionales = new HashSet<UnidadOrganizacional>();
            this.TipoOrigenId = this.TipoOrigenDefault;
        }

        [Prop(OrderIndex: 0, IsId: true, Required: true, Autogenerated: false, HTMLControl: PropAttribute.HTML_HIDDEN)]
        [Tbl(OrderIndex: 0, Visible: false)]
        public override string Id { get => base.Id; set => base.Id = value; }


        [Prop(OrderIndex: 1, Required: true)]
        [Tbl(OrderIndex: 1)]
        [ValidString(minlen: 1, maxlen: 100)]
        /// <summary>
        /// NOmbre de la unodad organizacional
        /// </summary>
        public string Nombre { get; set; }

        /// <summary>
        /// Identificador de relación de origem, en este caso se utiliza
        /// para vincular la unidad con su dueño en el modo MultiTenant 
        /// </summary>
        public string TipoOrigenId { get; set; }

        /// <summary>
        /// Identficador único del dueño, TENANT
        /// El Id de ralción es el identificador de un dominio
        /// </summary>
        public string OrigenId { get; set; }


        public ICollection<UnidadOrganizacional> UnidadesOrganizacionales { get; set; }
    }
}
